[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm_q3_2026 = "4ZRnPnXswZz8Ub7VByDzHiEGj7Bq8TzijafufN1tk4Rf"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
